insert into love_text (text) values ('Hold hender.                                                                                                                              ');
insert into love_text (text) values ('Gi komplimenter.                                                                                                                          ');
insert into love_text (text) values ('Hør på Billie Holiday.                                                                                                                    ');
insert into love_text (text) values ('Gi alltid parteneren din oppmerksom i hverdagen.                                                                                          ');
insert into love_text (text) values ('Kjøp en gave til kjæresten. Ingen anledning? Kjøpe noe allikevel.                                                                         ');
insert into love_text (text) values ('Server kaffe på sengen.                                                                                                                   ');
insert into love_text (text) values ('Eller få servert kaffe på sengen.                                                                                                         ');
insert into love_text (text) values ('Kyss mer. Og kyss offentlig.                                                                                                              ');
insert into love_text (text) values ('Fortell om dine innerste drømmer.                                                                                                         ');
insert into love_text (text) values ('Les Kaptein Corellis mandolin.                                                                                                            ');
insert into love_text (text) values ('Spør hvordan din kjære har det.                                                                                                           ');
insert into love_text (text) values ('Tenn levende lys. Hver kveld.                                                                                                             ');
insert into love_text (text) values ('Les noe av Paulo Coelho.                                                                                                                  ');
insert into love_text (text) values ('Se en romantisk film sammen: Topp 10 romantiske filmer                                                                                    ');
insert into love_text (text) values ('Vis beundring.                                                                                                                            ');
insert into love_text (text) values ('Planlegg (og spar til) en romantisk ferie.                                                                                                ');
insert into love_text (text) values ('Send koselige SMS-er hver dag.                                                                                                            ');
insert into love_text (text) values ('Spør din kjære hva han/hun ønsker seg. Notér det og ha planen klar for gavekjøp neste bursdag og jul.                                     ');
insert into love_text (text) values ('Si “Jeg er glad i deg” hver eneste dag.                                                                                                   ');
insert into love_text (text) values ('Se denne romantiske og rørende videoen med Daniel Jensen’s friere til  Gerda Marie Nedrebø eller søk på romantic proposal på YouTube.     ');
insert into love_text (text) values ('Skriv hyggelige beskjeder til din kjære på post it-lapper og fest én på baderomsspeilet, én på kaffemaskinen og én på utgangsdøren.       ');
insert into love_text (text) values ('Se på stjernene.                                                                                                                          ');
insert into love_text (text) values ('Husk hvorfor du valgte ham/henne.                                                                                                         ');
insert into love_text (text) values ('Ha champagnefrokost på sengen siste kvelden på weekendtur eller ferie.                                                                    ');
insert into love_text (text) values ('Masser hans/hennes vonde nakke.                                                                                                           ');
insert into love_text (text) values ('Vis respekt.                                                                                                                              ');
insert into love_text (text) values ('Planlegg pensjonisttilværelsen. Sammen.                                                                                                   ');
insert into love_text (text) values ('Lag et forførerisk soverom (med lys, duft, smak, symboler og farger).                                                                     ');
insert into love_text (text) values ('Send en sms og inviter din kjære til en date i kveld.                                                                                     ');
insert into love_text (text) values ('Bruk fint undertøy. Alltid.                                                                                                               ');
insert into love_text (text) values ('Les Romeo & Julie av William Shakespeare.                                                                                                 ');
insert into love_text (text) values ('Ha piknik i en park.                                                                                                                      ');
insert into love_text (text) values ('Lag en sexy drink til kjæresten din kommer fra jobb.                                                                                      ');
insert into love_text (text) values ('Feir bryllupsdagen hvert år.                                                                                                              ');
insert into love_text (text) values ('Bruk lekkert nattøy (kast den gamle slitte pysjen…).                                                                                      ');
insert into love_text (text) values ('Bli inspirert på Pinterest: I love kissing! og her: Me + You = Love                                                                       ');
insert into love_text (text) values ('Bruk de fine kjolene hjemme og ikke bare til fine anledninger.                                                                            ');
insert into love_text (text) values ('Gift deg. Eller gift deg på nytt med samme person…                                                                                        ');
insert into love_text (text) values ('La brudekjolen henge framme.                                                                                                              ');
insert into love_text (text) values ('Gå alltid til sengs samtidig.                                                                                                             ');
insert into love_text (text) values ('Lag en bildevegg med bilder av dere to.                                                                                                   ');
insert into love_text (text) values ('Lag sjokoladekuler med forførende ingredienser og del med din kjære.                                                                      ');
insert into love_text (text) values ('Kos og klem. Hver dag.                                                                                                                    ');
insert into love_text (text) values ('Spar den siste sjokoladen til ham/henne…                                                                                                  ');
insert into love_text (text) values ('Gi støtte på dårlige dager.                                                                                                               ');
insert into love_text (text) values ('Fisk etter komplimenter…                                                                                                                  ');
insert into love_text (text) values ('Ha en champagnefrokost.                                                                                                                   ');
insert into love_text (text) values ('Snakk bare pent om kjæresten din til andre.                                                                                               ');
insert into love_text (text) values ('Skal du på weekendtur? Pass på å reise til en romantisk by (Paris, Praha, Venezia, Tallin, Krakow, Edinburgh eller Roma…).                ');
insert into love_text (text) values ('Få parteneren din til å le.                                                                                                               ');
insert into love_text (text) values ('Lag en spilleliste med romantiske låter til din kjære.                                                                                    ');
insert into love_text (text) values ('Drikk kaffe på sengen sammen på en hverdagsmorgen.                                                                                        ');
insert into love_text (text) values ('Hør på Cocktail Chic Vol. 12 Paris Café (hos marianneprinsessen på Spotify) eller annen fransk romantisk musikk, for eksempel Stacey Kent.');
insert into love_text (text) values ('Sett deg ned og tenk på hvordan du kan få mer romantikk i forholdet og hverdagen…');

update love_text set text = trim(text);