insert into app_text (text,domain) values ('Gi komplimenter.                                                                                                                          ', 'LOVE');
insert into app_text (text,domain) values ('Hør på Billie Holiday.                                                                                                                    ', 'LOVE');
insert into app_text (text,domain) values ('Gi alltid parteneren din oppmerksom i hverdagen.                                                                                          ', 'LOVE');
insert into app_text (text,domain) values ('Kjøp en gave til kjæresten. Ingen anledning? Kjøpe noe allikevel.                                                                         ', 'LOVE');
insert into app_text (text,domain) values ('Server kaffe på sengen.                                                                                                                   ', 'LOVE');
insert into app_text (text,domain) values ('Eller få servert kaffe på sengen.                                                                                                         ', 'LOVE');
insert into app_text (text,domain) values ('Kyss mer. Og kyss offentlig.                                                                                                              ', 'LOVE');
insert into app_text (text,domain) values ('Fortell om dine innerste drømmer.                                                                                                         ', 'LOVE');
insert into app_text (text,domain) values ('Les Kaptein Corellis mandolin.                                                                                                            ', 'LOVE');
insert into app_text (text,domain) values ('Spør hvordan din kjære har det.                                                                                                           ', 'LOVE');
insert into app_text (text,domain) values ('Tenn levende lys. Hver kveld.                                                                                                             ', 'LOVE');
insert into app_text (text,domain) values ('Les noe av Paulo Coelho.                                                                                                                  ', 'LOVE');
insert into app_text (text,domain) values ('Se en romantisk film sammen: Topp 10 romantiske filmer                                                                                    ', 'LOVE');
insert into app_text (text,domain) values ('Vis beundring.                                                                                                                            ', 'LOVE');
insert into app_text (text,domain) values ('Planlegg (og spar til) en romantisk ferie.                                                                                                ', 'LOVE');
insert into app_text (text,domain) values ('Send koselige SMS-er hver dag.                                                                                                            ', 'LOVE');
insert into app_text (text,domain) values ('Spør din kjære hva han/hun ønsker seg. Notér det og ha planen klar for gavekjøp neste bursdag og jul.                                     ', 'LOVE');
insert into app_text (text,domain) values ('Si “Jeg er glad i deg” hver eneste dag.                                                                                                   ', 'LOVE');
insert into app_text (text,domain) values ('Se denne romantiske og rørende videoen med Daniel Jensen’s friere til  Gerda Marie Nedrebø eller søk på romantic proposal på YouTube.     ', 'LOVE');
insert into app_text (text,domain) values ('Skriv hyggelige beskjeder til din kjære på post it-lapper og fest én på baderomsspeilet, én på kaffemaskinen og én på utgangsdøren.       ', 'LOVE');
insert into app_text (text,domain) values ('Se på stjernene.                                                                                                                          ', 'LOVE');
insert into app_text (text,domain) values ('Husk hvorfor du valgte ham/henne.                                                                                                         ', 'LOVE');
insert into app_text (text,domain) values ('Ha champagnefrokost på sengen siste kvelden på weekendtur eller ferie.                                                                    ', 'LOVE');
insert into app_text (text,domain) values ('Masser hans/hennes vonde nakke.                                                                                                           ', 'LOVE');
insert into app_text (text,domain) values ('Vis respekt.                                                                                                                              ', 'LOVE');
insert into app_text (text,domain) values ('Planlegg pensjonisttilværelsen. Sammen.                                                                                                   ', 'LOVE');
insert into app_text (text,domain) values ('Lag et forførerisk soverom (med lys, duft, smak, symboler og farger).                                                                     ', 'LOVE');
insert into app_text (text,domain) values ('Send en sms og inviter din kjære til en date i kveld.                                                                                     ', 'LOVE');
insert into app_text (text,domain) values ('Bruk fint undertøy. Alltid.                                                                                                               ', 'LOVE');
insert into app_text (text,domain) values ('Les Romeo & Julie av William Shakespeare.                                                                                                 ', 'LOVE');
insert into app_text (text,domain) values ('Ha piknik i en park.                                                                                                                      ', 'LOVE');
insert into app_text (text,domain) values ('Lag en sexy drink til kjæresten din kommer fra jobb.                                                                                      ', 'LOVE');
insert into app_text (text,domain) values ('Feir bryllupsdagen hvert år.                                                                                                              ', 'LOVE');
insert into app_text (text,domain) values ('Bruk lekkert nattøy (kast den gamle slitte pysjen…).                                                                                      ', 'LOVE');
insert into app_text (text,domain) values ('Bli inspirert på Pinterest: I love kissing! og her: Me + You = Love                                                                       ', 'LOVE');
insert into app_text (text,domain) values ('Bruk de fine kjolene hjemme og ikke bare til fine anledninger.                                                                            ', 'LOVE');
insert into app_text (text,domain) values ('Gift deg. Eller gift deg på nytt med samme person…                                                                                        ', 'LOVE');
insert into app_text (text,domain) values ('La brudekjolen henge framme.                                                                                                              ', 'LOVE');
insert into app_text (text,domain) values ('Gå alltid til sengs samtidig.                                                                                                             ', 'LOVE');
insert into app_text (text,domain) values ('Spar den siste sjokoladen til ham/henne…                                                                                                  ', 'LOVE');
insert into app_text (text,domain) values ('Gi støtte på dårlige dager.                                                                                                               ', 'LOVE');
insert into app_text (text,domain) values ('Fisk etter komplimenter…                                                                                                                  ', 'LOVE');
insert into app_text (text,domain) values ('Ha en champagnefrokost.                                                                                                                   ', 'LOVE');
insert into app_text (text,domain) values ('Snakk bare pent om kjæresten din til andre.                                                                                               ', 'LOVE');
insert into app_text (text,domain) values ('Skal du på weekendtur? Pass på å reise til en romantisk by (Paris, Praha, Venezia, Tallin, Krakow, Edinburgh eller Roma…).                ', 'LOVE');
insert into app_text (text,domain) values ('Få parteneren din til å le.                                                                                                               ', 'LOVE');
insert into app_text (text,domain) values ('Lag en spilleliste med romantiske låter til din kjære.                                                                                    ', 'LOVE');
insert into app_text (text,domain) values ('Drikk kaffe på sengen sammen på en hverdagsmorgen.                                                                                        ', 'LOVE');
insert into app_text (text,domain) values ('Hør på Cocktail Chic Vol. 12 Paris Café (hos marianneprinsessen på Spotify) eller annen fransk romantisk musikk, for eksempel Stacey Kent.', 'LOVE');
insert into app_text (text,domain) values ('Lag en bildevegg med bilder av dere to.                                                                                                   ', 'LOVE');
insert into app_text (text,domain) values ('Sett deg ned og tenk på hvordan du kan få mer romantikk i forholdet og hverdagen…', 'LOVE');
insert into app_text (text,domain) values ('Lag sjokoladekuler med forførende ingredienser og del med din kjære.                                                                      ', 'LOVE');
insert into app_text (text,domain) values ('Kos og klem. Hver dag.                                                                                                                    ', 'LOVE');
insert into app_text (text,domain) values ('Hold hender.                                                                                                                              ', 'LOVE');

update app_text set text = trim(text);

